name: Build & Test

on:
  - push
  - pull_request

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5
      
      - run: wget https://apt.llvm.org/llvm.sh && 
            chmod +x llvm.sh &&
            sudo ./llvm.sh 16


      - run: opam install . --deps-only --no-depexts --with-test

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest
